### ISSUE TITLE
Issue with Author URL

### ISSUE THREAD

**Issue by InfoDevkota** [Classof2020/classof2020.github.io#35]
http://ww1.classof2020.xyz/blog/ When ever clicking in the author link it gives a dead link. I figure out that to solve this issue we should add http:// or https:// in before of the URL in every post. Or Any Expert here can make some script on the blog template it should do something like (adding http automatically if it is missed in the url section. If it is present let it be.) However I try to fix a  that with the method I know. with the  pull request https://github.com/Classof2020/classof2020.github.io/pull/34 @NischalLalShrestha  Look through it....

**Comment by theonlyNischal** [comment]
Yeah, We should use the complete address, otherwise, it leads us to a dead link.

**Comment by MegaMind98** [comment]
Inadvertently missed this issue. Is the problem you're suggesting fixed with that #34, @InfoDevkota? Let me know. Thanks!

**Comment by InfoDevkota** [comment]
I was thinking about using the absolute url there. @NischalLalShrestha manage it to solve by using the relative path url that looks fine. Thanks!
