### ISSUE TITLE
Thoughts on Tutorial Section

### ISSUE THREAD

**Issue by MegaMind98** [Classof2020/classof2020.github.io#37]
We have blog section on the website where we can speak our heart and mind. 

Having said that, I still do support the idea of making a dedicated 'Tutorial' page. However we already do have categories in our blog template. I was thinking if we could utilize that and categorize our blog posts within itself for better navigation (like tutorial and ramblings, etc). Because on the surface, both imply the same thing. 

Let me know what you think @NischalLalShrestha, @InfoDevkota, @developersanjog, @PrabinSingh.

Thanks!

**Comment by PrabinSingh** [comment]
Thanks for giving me a chance i am glad to talk .

**Comment by MegaMind98** [comment]
Please know that we're glad that you're by our side. @PrabinSingh

**Comment by developersanjog** [comment]
I believe in simplicity and always will , either a platform must be
extremely simple or extremely complex . The simple are for normal users and
complex are for programmers.
So i suggest to make our blog in such a way that we must type codes to run
that.

**Comment by InfoDevkota** [comment]
Looking back to the time when we plan to add blog section, is to share idea (whatever they are speak out heart and mind or share what we know). Ya as you mentioned for tutorial we could use categorize. Simple is always batter then complex. What I say is let  @NischalLalShrestha decide what to do. He is the one who believe in "sharing is caring".

**Comment by MegaMind98** [comment]
Leaving this to @NischalLalShrestha!
