### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PrabinSingh** [Classof2020/classof2020.github.io#38]
![screenshot 18](https://user-images.githubusercontent.com/24428921/28635443-5b77ad06-725a-11e7-8ada-a9c55b61232f.png)

**Comment by InfoDevkota** [comment]
That look fine and working, Just browse http://127.0.0.1:4000/ I don't think its not working.

**Comment by PrabinSingh** [comment]
why this not working

**Comment by MegaMind98** [comment]
I've added a favicon, fixed this!
